/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transfer.main;

import java.awt.event.ActionEvent;
import java.io.File;
import java.net.InetSocketAddress;
import javax.swing.JFileChooser;
import transfer.thread.SendThread;

/**
 *
 * @author circlehotarux
 */
public class SubUI extends javax.swing.JPanel {
    private String ip;
    
    /**
     * Creates new form SubUI
     */
    public SubUI(String ip) {
        initComponents();
        this.ip = ip;
        label_ip.setText(ip);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_send = new javax.swing.JButton();
        label_ip = new javax.swing.JLabel();

        button_send.setText("发送");
        button_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_send)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_send))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    //发送文件
    private void button_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sendActionPerformed
        // 打开文件选择对话框
        JFileChooser MyJFileChooser=new JFileChooser();
        MyJFileChooser.setDialogTitle("选择发送文件");
        MyJFileChooser.setApproveButtonText("选择");
        MyJFileChooser.setFileSelectionMode(MyJFileChooser.FILES_ONLY);
        MyJFileChooser.setMultiSelectionEnabled(false);
        int result=MyJFileChooser.showOpenDialog(this);     //显示对话框
        if(result==JFileChooser.APPROVE_OPTION){
            File selectedFile= MyJFileChooser.getSelectedFile();
            //--test
            System.out.println(selectedFile.getAbsoluteFile());
            System.out.println(selectedFile.getName());
            System.out.println(selectedFile.length());
            //--test
            //开启文件传输线程--附带进度条面板
            InetSocketAddress address=new InetSocketAddress(this.label_ip.getText(),54199);
            System.out.println(address.getAddress().getHostAddress());
            new SendThread(selectedFile,address).start();
        };
    }//GEN-LAST:event_button_sendActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_send;
    private javax.swing.JLabel label_ip;
    // End of variables declaration//GEN-END:variables
}
